#!/usr/bin/ruby

unless File.exists?('.projectFileMap')
  puts "'.projectFileMap' not found. Please run indexify first."
  exit(1)
end

File.open(".projectFileMap", "r").each_line do
  |line|
  filename = line.split(':')[-1]
  `touch '#{filename.chomp}'`
  puts "touching #{filename.chomp}"
end

`touch README.md && echo \"\# This is the root directory for a project for Holberton School\" > README.md`
puts "touching README.md"
puts "Done"


