#!/usr/bin/ruby

unless File.exists?('.projectFileMap')
  puts "'.projectFileMap' not found. Please run indexify first."
  exit(1)
end

File.open(".projectFileMap", "r").each_line do
  |line|
  filename = line.split(':')[-1]
  `touch '#{filename.chomp}'`
  puts "touching #{filename.chomp}"
end

puts "Done"


