#!/usr/bin/ruby

puts "Please paste webpage. Press ^D (Ctrl+d on windows-based machines) when you're done."

File.open(".projectText", "w") do
  |f|
  x = gets()
  while(x)
    f.puts(x)
    x = gets()
  end
end


File.open(".projectMap", "w") do
  |map|
  currentproject = 0
  File.open(".projectText","r").each_line do
    |line|
    myMatch = line.match(/^(\d+)\. .*$/)
    currentproject = myMatch[1] if myMatch

    fileMatch = line.match(/ File: (.*)$/)
    map.puts currentproject.to_s + ":" + fileMatch[1] if fileMatch
    
  end
end


